include:
  - project: 'vulners/infra/gitlab-ci'
    ref: main
    file: deploy.yaml

variables:
  COMMIT_IMAGE: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}
  LATEST_IMAGE: ${CI_REGISTRY_IMAGE}:latest

stages:
  - build
  - deploy
  - sync

build:
  extends: .build-template

deploy:prod:
  extends: .deploy_template_argocd
  needs: ["build"]
  stage: deploy
  variables:
    APP: vulners_mcp
    TARGET_IMAGE: ${COMMIT_IMAGE}

sync:prod:api:
  extends: .deploy_cluster_sync_template
  stage: sync
  needs: ["deploy:prod"]